### ISSUE TITLE
Can't apply patch

### ISSUE THREAD

**Issue by pke** [bluekeyes/patch2pr#49]
Tried to create a PR for a patch generated by nodejs `patch-package` module. This tool checks out a clean copy of the module to be patched and diffs it with the changes in the modules node_modules folder hirarchy. The resulting patch is saved to `patches/module.name.patch`

I used this patch to run `patch2pr` and got this error:

```
patch2pr -repository mrousavy/react-native-vision-camera patches/react-native-vision-camera+2.15.4.patch
error: apply failed: node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt: no entry for modified file
```

**Comment by bluekeyes** [comment]
Is it possible to share the patch you created that failed to apply? That will make it easier to debug this problem.

Based on your description and the error, I think the problem is that `patch-package` creates patches that are meant to apply to installed copies of libraries and not to the upstream source repositories of the libraries.

From the output, you can see that it's trying to modify a file in the `node_modules/react-native-vision-camera` directory, but this directory only exists after you run `npm install react-native-vision-camera` in a project. If you look at the [upstream repository](https://github.com/mrousavy/react-native-vision-camera), the `android` directory exists at the root and there's no `node_modules` directory.

You might be able to fix this by pre-processing the patch to change the paths, maybe something like:

    sed 's|mrousavy/react-native-vision-camera/||g' patches/react-native-vision-camera+2.15.4.patch | patch2pr -repository mrousavy/react-native-vision-camera

But in general, installing an npm package extracts an archive that is derived (maybe via a build process) from the upstream source repository, so there's no guarantee that the files you have in your `node_modules` directory exist in the source.

A final note: `patch2pr` requires write permissions on the repository to create a PR, so you'll need to create a fork and target your fork with the `-repository` flag if you are not a contributor on the original repository.

**Comment by pke** [comment]
Ah thanks that makes so much more sense now! Yes the patch is generated upon the distributed set of files, not the actual source files. That explains it.

Also I missed the part that I need to create a fork first and stream my PR into that, but I should have known, since that is the default PR flow anway.

Thanks I will close this and try the `sed` solution.
